/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AwButton: typeof import('./components/Lv2_Molecules/AwButton.vue')['default']
    AwHeader: typeof import('./components/Lv4_Organisms/AwHeader.vue')['default']
    AwInput: typeof import('./components/Lv1_Atoms/AwInput.vue')['default']
    AwItemLg: typeof import('./components/Lv2_Molecules/AwItemLg.vue')['default']
    AwItemSm: typeof import('./components/Lv2_Molecules/AwItemSm.vue')['default']
    AwLogo: typeof import('./components/Lv1_Atoms/AwLogo.vue')['default']
    AwNavbar: typeof import('./components/Lv2_Molecules/AwNavbar.vue')['default']
    AwNoteEditor: typeof import('./components/Lv4_Organisms/AwNoteEditor.vue')['default']
    AwNoteInfo: typeof import('./components/Lv2_Molecules/AwNoteInfo.vue')['default']
    AwNoteView: typeof import('./components/Lv4_Organisms/AwNoteView.vue')['default']
    AwPage: typeof import('./components/shared/AwPage/AwPage.vue')['default']
    AwSelectNote: typeof import('./components/Lv2_Molecules/AwSelectNote.vue')['default']
    AwSidebar: typeof import('./components/Lv5_Templates/AwSidebar.vue')['default']
    AwText: typeof import('./components/Lv1_Atoms/AwText.vue')['default']
    MoreActions: typeof import('./components/Lv4_Organisms/MoreActions.vue')['default']
    NoteAction: typeof import('./components/Lv2_Molecules/NoteAction.vue')['default']
    NoteFolder: typeof import('./components/Lv4_Organisms/NoteFolder.vue')['default']
    NotesList: typeof import('./components/Lv4_Organisms/NotesList.vue')['default']
    PageDesktop: typeof import('./components/shared/AwPage/sub/PageDesktop.vue')['default']
    PageMobile: typeof import('./components/shared/AwPage/sub/PageMobile.vue')['default']
    PageTablet: typeof import('./components/shared/AwPage/sub/WrapperMd.vue')['default']
    RecentNotes: typeof import('./components/Lv4_Organisms/RecentNotes.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WrapperLg: typeof import('./components/shared/WrapperLg.vue')['default']
    WrapperMd: typeof import('./components/shared/WrapperMd.vue')['default']
    WrapperSm: typeof import('./components/shared/WrapperSm.vue')['default']
  }
}
